# Generated by Django 6.1 on 2026-09-22 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['criado_em'], 'verbose_name': 'usuário', 'verbose_name_plural': 'usuários'},
        ),
    ]
