# Generated by Django 6.1 on 2026-09-22 12:07

import apps.usuarios.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuario_options'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('objects', apps.usuarios.models.UsuarioManager()),
            ],
        ),
    ]
